import Head from "next/head";
import { NavBar, Rides } from "../components";
import { rides } from "../components/temp";
import { cleanRidesData } from "../lib/fns";
// import UserService from "../services/UserService";
const user = {
  name: "Malcolm Parker",
  station_code: 51,
  url: "https://picsum.photos/200",
};
// export async function getServerSideProps() {
//   const response = await UserService.getUser();

//   if (!response.data) {
//     return {
//       notFound: true,
//     };
//   }

//   return {
//     props: {
//       user: response.data,
//       revalidate: 600,
//     },
//   };
// }

export async function getStaticProps() {
  return {
    props: {
      rides,
      user,
    },
  };
}

export default function Home({ rides, user }) {
  return (
    <div>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar user={user} />
        <Rides
          allRides={cleanRidesData(rides, user.station_code)}
          user={user}
        />
      </main>
    </div>
  );
}
