import Head from "next/head";
import { NavBar } from "../components";
import UserService from "../Services/UserService";

export async function getServerSideProps() {
  const response = await UserService.getUser();

  if (!response.data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user: response.data,
      revalidate: 600,
    },
  };
}

export default function Home({ user }) {
  return (
    <div>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar user={user} />
      </main>
    </div>
  );
}
